# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Project name')),
                ('website', models.CharField(max_length=254, verbose_name='Project website')),
                ('owner_name', models.CharField(max_length=254, verbose_name='Project owner')),
                ('owner_email', models.EmailField(max_length=254, verbose_name='Owner email')),
                ('creation_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
